### PR TITLE
Update cherry_picker_test.md

### PR DESCRIPTION
**Pull request by wuhuizuo**
### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:

### Check List 

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
Please add a release note, or a 'None' if it is not needed.
```

### CODE REVIEW

**Comment by wuhuizuo** [comment]
@zuo-bot-2 please review it

**Review by zuo-bot-2 — APPROVED** [review]

**Review by zuo-bot-2 — CHANGES_REQUESTED** [review]
hahah

**Review by zuo-bot-2 — CHANGES_REQUESTED** [review]
123

**Review by zuo-bot-2 — APPROVED** [review]

**Review by zuo-bot-2 — APPROVED** [review]

**Review by zuo-bot-2 — APPROVED** [review]
/lgtm cancel

**Review by zuo-bot-2 — COMMENTED** [review]
/lgtm

**Review by zuo-bot-2 — APPROVED** [review]

**Review by zuo-bot-2 — CHANGES_REQUESTED** [review]
please change

**Review by zuo-bot-2 — APPROVED** [review]
/lgtm

**Review by zuo-bot-2 — CHANGES_REQUESTED** [review]
need change

**Review by zuo-bot-2 — APPROVED** [review]

**Pull request closed without merging**
